version: "3.8"
services:
  upa-hello:
    container_name: upa-hello
    image: xiangzhedev/upgradeall-server
    restart: unless-stopped
    labels:
      "io.containers.autoupdate": "image"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    command: hello
    environment:
      - discovery_url=tcp://upa-proxy:5256
      - database_url=upa@upa-db:3306

    ports:
      - "5255:5255"
    depends_on:
      - upa-proxy
      - upa-getter
    networks:
      - upanet
  upa-proxy:
    container_name: upa-proxy
    image: xiangzhedev/upgradeall-server
    restart: unless-stopped
    labels:
      "io.containers.autoupdate": "image"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    command: discovery --bind 'tcp://upa-proxy:5256'
    expose:
      - "1-65535:1-65535"
    networks:
      - upanet
  upa-getter:
    container_name: upa-getter
    image: xiangzhedev/upgradeall-server
    restart: unless-stopped
    labels:
      "io.containers.autoupdate": "image"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    command: getter -r 'tcp://upa-proxy:5256' -b 'tcp://upa-getter:(5257)' -db 'upa@upa-db:3306'
    networks:
      - upanet
    depends_on:
      - upa-db
      - upa-proxy
  upa-db:
    container_name: upa-db
    image: mariadb
    restart: unless-stopped
    labels:
      "io.containers.autoupdate": "image"
    env_file:
      - db.env
    expose:
      - "3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - upanet
volumes:
  dbdata:
    name: upa-dbdata
networks:
  upanet:
