version: "3.8"
services:
  upa-hello:
    container_name: upa-hello
    image: xiangzhedev/upgradeall-server
    restart: unless-stopped
    labels:
      "io.containers.autoupdate": "image"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    command: hello
    ports:
      - "5255:5255"
    depends_on:
      - upa-proxy
      - upa-getter
    volumes:
      - tmpdata:/tmp/upa
    networks:
      - upanet
  upa-proxy:
    container_name: upa-proxy
    image: xiangzhedev/upgradeall-server
    restart: unless-stopped
    labels:
      "io.containers.autoupdate": "image"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    command: discovery
    expose:
      - "5559"
      - "5560"
    volumes:
      - tmpdata:/tmp/upa
    networks:
      - upanet
  upa-getter:
    container_name: upa-getter
    image: xiangzhedev/upgradeall-server
    restart: unless-stopped
    labels:
      "io.containers.autoupdate": "image"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    command: getter
    volumes:
      - tmpdata:/tmp/upa
    networks:
      - dbnet
      - upanet
    depends_on:
      - upa-db
      - upa-proxy
  upa-db:
    container_name: upa-db
    image: mariadb
    restart: unless-stopped
    labels:
      "io.containers.autoupdate": "image"
    env_file:
      - db.env
    expose:
      - "3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - dbnet
volumes:
  dbdata:
    name: upa-dbdata
  tmpdata:
    name: upa-tmp
networks:
  dbnet:
  upanet:
