# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from app.grpc_server import route_pb2 as app_dot_grpc__server_dot_route__pb2


class UpdateServerRouteStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReleaseInfo = channel.unary_unary(
                '/routeguide.UpdateServerRoute/GetReleaseInfo',
                request_serializer=app_dot_grpc__server_dot_route__pb2.AppInfo.SerializeToString,
                response_deserializer=app_dot_grpc__server_dot_route__pb2.ReturnValue.FromString,
                )


class UpdateServerRouteServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetReleaseInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpdateServerRouteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReleaseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReleaseInfo,
                    request_deserializer=app_dot_grpc__server_dot_route__pb2.AppInfo.FromString,
                    response_serializer=app_dot_grpc__server_dot_route__pb2.ReturnValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routeguide.UpdateServerRoute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UpdateServerRoute(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetReleaseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.UpdateServerRoute/GetReleaseInfo',
            app_dot_grpc__server_dot_route__pb2.AppInfo.SerializeToString,
            app_dot_grpc__server_dot_route__pb2.ReturnValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
