# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from app.grpc_server import route_pb2 as app_dot_grpc__server_dot_route__pb2


class UpdateServerRouteStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAppStatus = channel.unary_unary(
                '/server_route.UpdateServerRoute/GetAppStatus',
                request_serializer=app_dot_grpc__server_dot_route__pb2.Request.SerializeToString,
                response_deserializer=app_dot_grpc__server_dot_route__pb2.AppStatus.FromString,
                )
        self.GetAppStatusList = channel.unary_unary(
                '/server_route.UpdateServerRoute/GetAppStatusList',
                request_serializer=app_dot_grpc__server_dot_route__pb2.RequestList.SerializeToString,
                response_deserializer=app_dot_grpc__server_dot_route__pb2.ResponseList.FromString,
                )
        self.GetDownloadInfo = channel.unary_unary(
                '/server_route.UpdateServerRoute/GetDownloadInfo',
                request_serializer=app_dot_grpc__server_dot_route__pb2.DownloadAssetIndex.SerializeToString,
                response_deserializer=app_dot_grpc__server_dot_route__pb2.DownloadInfo.FromString,
                )


class UpdateServerRouteServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetAppStatus(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppStatusList(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDownloadInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpdateServerRouteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAppStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppStatus,
                    request_deserializer=app_dot_grpc__server_dot_route__pb2.Request.FromString,
                    response_serializer=app_dot_grpc__server_dot_route__pb2.AppStatus.SerializeToString,
            ),
            'GetAppStatusList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppStatusList,
                    request_deserializer=app_dot_grpc__server_dot_route__pb2.RequestList.FromString,
                    response_serializer=app_dot_grpc__server_dot_route__pb2.ResponseList.SerializeToString,
            ),
            'GetDownloadInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDownloadInfo,
                    request_deserializer=app_dot_grpc__server_dot_route__pb2.DownloadAssetIndex.FromString,
                    response_serializer=app_dot_grpc__server_dot_route__pb2.DownloadInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_route.UpdateServerRoute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UpdateServerRoute(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetAppStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server_route.UpdateServerRoute/GetAppStatus',
            app_dot_grpc__server_dot_route__pb2.Request.SerializeToString,
            app_dot_grpc__server_dot_route__pb2.AppStatus.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAppStatusList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server_route.UpdateServerRoute/GetAppStatusList',
            app_dot_grpc__server_dot_route__pb2.RequestList.SerializeToString,
            app_dot_grpc__server_dot_route__pb2.ResponseList.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDownloadInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server_route.UpdateServerRoute/GetDownloadInfo',
            app_dot_grpc__server_dot_route__pb2.DownloadAssetIndex.SerializeToString,
            app_dot_grpc__server_dot_route__pb2.DownloadInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
