# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/grpc_server/route.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/grpc_server/route.proto',
  package='routeguide',
  syntax='proto3',
  serialized_options=b'\n\036net.xzos.upgradeall.core.routeB\nRouteProtoP\001',
  serialized_pb=b'\n\x1b\x61pp/grpc_server/route.proto\x12\nrouteguide\"F\n\x07\x41ppInfo\x12\x10\n\x08hub_uuid\x18\x01 \x01(\t\x12)\n\x08\x61pp_info\x18\x02 \x03(\x0b\x32\x17.routeguide.AppInfoItem\")\n\x0b\x41ppInfoItem\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"k\n\x0bReturnValue\x12\x16\n\x0evalid_hub_uuid\x18\x01 \x01(\x08\x12\x11\n\tvalid_app\x18\x02 \x01(\x08\x12\x31\n\x0crelease_info\x18\x03 \x03(\x0b\x32\x1b.routeguide.ReleaseInfoItem\"d\n\x0fReleaseInfoItem\x12\x16\n\x0eversion_number\x18\x01 \x01(\t\x12\x12\n\nchange_log\x18\x02 \x01(\t\x12%\n\x06\x61ssets\x18\x03 \x03(\x0b\x32\x15.routeguide.AssetItem\"G\n\tAssetItem\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x14\n\x0c\x64ownload_url\x18\x02 \x01(\t\x12\x11\n\tfile_type\x18\x03 \x01(\t2U\n\x11UpdateServerRoute\x12@\n\x0eGetReleaseInfo\x12\x13.routeguide.AppInfo\x1a\x17.routeguide.ReturnValue\"\x00\x42.\n\x1enet.xzos.upgradeall.core.routeB\nRouteProtoP\x01\x62\x06proto3'
)




_APPINFO = _descriptor.Descriptor(
  name='AppInfo',
  full_name='routeguide.AppInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hub_uuid', full_name='routeguide.AppInfo.hub_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_info', full_name='routeguide.AppInfo.app_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=113,
)


_APPINFOITEM = _descriptor.Descriptor(
  name='AppInfoItem',
  full_name='routeguide.AppInfoItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='routeguide.AppInfoItem.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='routeguide.AppInfoItem.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=156,
)


_RETURNVALUE = _descriptor.Descriptor(
  name='ReturnValue',
  full_name='routeguide.ReturnValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid_hub_uuid', full_name='routeguide.ReturnValue.valid_hub_uuid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_app', full_name='routeguide.ReturnValue.valid_app', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='release_info', full_name='routeguide.ReturnValue.release_info', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=265,
)


_RELEASEINFOITEM = _descriptor.Descriptor(
  name='ReleaseInfoItem',
  full_name='routeguide.ReleaseInfoItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version_number', full_name='routeguide.ReleaseInfoItem.version_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='change_log', full_name='routeguide.ReleaseInfoItem.change_log', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assets', full_name='routeguide.ReleaseInfoItem.assets', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=367,
)


_ASSETITEM = _descriptor.Descriptor(
  name='AssetItem',
  full_name='routeguide.AssetItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='routeguide.AssetItem.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='download_url', full_name='routeguide.AssetItem.download_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_type', full_name='routeguide.AssetItem.file_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=440,
)

_APPINFO.fields_by_name['app_info'].message_type = _APPINFOITEM
_RETURNVALUE.fields_by_name['release_info'].message_type = _RELEASEINFOITEM
_RELEASEINFOITEM.fields_by_name['assets'].message_type = _ASSETITEM
DESCRIPTOR.message_types_by_name['AppInfo'] = _APPINFO
DESCRIPTOR.message_types_by_name['AppInfoItem'] = _APPINFOITEM
DESCRIPTOR.message_types_by_name['ReturnValue'] = _RETURNVALUE
DESCRIPTOR.message_types_by_name['ReleaseInfoItem'] = _RELEASEINFOITEM
DESCRIPTOR.message_types_by_name['AssetItem'] = _ASSETITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppInfo = _reflection.GeneratedProtocolMessageType('AppInfo', (_message.Message,), {
  'DESCRIPTOR' : _APPINFO,
  '__module__' : 'app.grpc_server.route_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.AppInfo)
  })
_sym_db.RegisterMessage(AppInfo)

AppInfoItem = _reflection.GeneratedProtocolMessageType('AppInfoItem', (_message.Message,), {
  'DESCRIPTOR' : _APPINFOITEM,
  '__module__' : 'app.grpc_server.route_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.AppInfoItem)
  })
_sym_db.RegisterMessage(AppInfoItem)

ReturnValue = _reflection.GeneratedProtocolMessageType('ReturnValue', (_message.Message,), {
  'DESCRIPTOR' : _RETURNVALUE,
  '__module__' : 'app.grpc_server.route_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.ReturnValue)
  })
_sym_db.RegisterMessage(ReturnValue)

ReleaseInfoItem = _reflection.GeneratedProtocolMessageType('ReleaseInfoItem', (_message.Message,), {
  'DESCRIPTOR' : _RELEASEINFOITEM,
  '__module__' : 'app.grpc_server.route_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.ReleaseInfoItem)
  })
_sym_db.RegisterMessage(ReleaseInfoItem)

AssetItem = _reflection.GeneratedProtocolMessageType('AssetItem', (_message.Message,), {
  'DESCRIPTOR' : _ASSETITEM,
  '__module__' : 'app.grpc_server.route_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.AssetItem)
  })
_sym_db.RegisterMessage(AssetItem)


DESCRIPTOR._options = None

_UPDATESERVERROUTE = _descriptor.ServiceDescriptor(
  name='UpdateServerRoute',
  full_name='routeguide.UpdateServerRoute',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=442,
  serialized_end=527,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetReleaseInfo',
    full_name='routeguide.UpdateServerRoute.GetReleaseInfo',
    index=0,
    containing_service=None,
    input_type=_APPINFO,
    output_type=_RETURNVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPDATESERVERROUTE)

DESCRIPTOR.services_by_name['UpdateServerRoute'] = _UPDATESERVERROUTE

# @@protoc_insertion_point(module_scope)
