version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile_docker-compose
    container_name: update-server
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./server/config.ini:/config.ini
    network_mode: "host"

  redis:
    image: redis
    container_name: update-server_redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    network_mode: "host"
