name: Build and Push Docker image
on: 
  push:
    branches:
    - master
    workflow_dispatch:
jobs:
  Build:
    runs-on: 
    - ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
          docker build . --file oci_build/Dockerfile --tag johnsonran/upgradeall-server:latest

    - name: Login DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.HUB_USR }}
          password: ${{ secrets.HUB_TKN }}

    - name: Push to DockerHub
      run: |
          docker push johnsonran/upgradeall-server:latest